spring.application.name=demo

# Enlace JDBC al esquema físico creado en DBeaver
spring.datasource.url=jdbc:mysql://localhost:3306/banco_tp2?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Directivas del Almacén del Dominio (Hibernate DDL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true