spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/banco_tp2?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: banco_user
    password: admin123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        orm:
          boot: DEBUG
        tool:
          schema: DEBUG