spring:
  application:
    name: demo

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/banco_tp2?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USERNAME:banco_user}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE